### ISSUE TITLE
Uncertainty in function return types is lost

### ISSUE THREAD

**Issue by glguy** [jmid/luata-quickcheck#10]
The analysis seems to be confident that `c` is going to have a `number` type instead of the actual `nil` type. The analysis correctly identifies that the second return value might have number type (based on my understanding of the question mark) `? { number:   Top }` however the analysis seems to give the wrong confidence to the type of `b` with `! { number:   Top }`

```
local function f(x)
        if x > 10 then
                return 1,2 
        else
                return 3
        end 
end

a,b=f(0)
c=type(b)
print(c)
```

Expected output:

```
$ lua mytest.lua
nil
```

**Comment by jmid** [comment]
Thanks for the report! 
I must have mis-interpreted how the manual states that 
 metatable(obj)[event] should be interpreted as rawget(getmetatable(obj) or {}, event) 
at http://www.lua.org/manual/5.1/manual.html#2.8

**Comment by glguy** [comment]
I think that the next statement that "The code shown here in Lua is only illustrative; the real behavior is hard coded in the interpreter and it is much more efficient than this simulation." in what invalidates your otherwise perfectly reasonable interpretation of the documentation.

It seems like we might consider this a bug in either the documentation or the implementation. They certainly don't seem to match. This issue has since been resolved. Note that Lua 5.3 no longer includes that sample code.

Also, I think these last two comments were meant for #9

**Comment by jmid** [comment]
Yes, these were indeed meant for #9 :-)
Thanks for this one as well. It exposes a hackish work-around I did in propagating return information.
I'll think a bit about how to fix it properly...

**Comment by jmid** [comment]
I finally got around to fixing this one, which happened to be an easier fix than I had first imagined.
Thanks for the report!
