### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by dapetcu21** [jmid/luata-quickcheck#13]
Hi!

I'm working on an editor plugin for Lua ([atom-autocomplete-lua](https://github.com/dapetcu21/atom-autocomplete-lua)) and I would like to rewrite it using proper lattices. It would be really helpful to be able to use some of the code from this repo (especially the lexer and parser), but I can't do that because there is no license on this repo. Might you consider adding a LICENSE file? Maybe something permissive like the [MIT license](https://opensource.org/licenses/MIT)?

**Comment by jmid** [comment]
Thanks for your interest in this project. You are welcome to reuse parts of it. I've just added a 2-clause BSD license. atom-autocomplete-lua looks cool!
