### ISSUE TITLE
__metatable is considered when resolving metamethods

### ISSUE THREAD

**Issue by glguy** [jmid/luata-quickcheck#9]
It appears that the `__metatable` field of a metatable is considered when resolving metamethods. (At least in Lua 5.1, 5.2 and 5.3) it is the case that `__metatable` is only consulted when calling the `getmetatable` built-in from Lua code. It is not consulted when resolving actual metamethods. It exists only as a protection mechanism for metatables, and not for overloading them from the point of view of Lua.

This discrepancy causes `luata` to produce incorrect output for code using the `__metatable` metamethod.

```
local complexMt = { __metatable = "Complex number metatable protected" }

local function Complex(real,imag)
   local n = {real = real, imag = imag}
   setmetatable(n, complexMt)
   return n
end

function complexMt.__add(x,y)
   return Complex(x.real + y.real, x.imag + y.imag)
end

function complexMt:__tostring()
   return self.real .. "+" .. self.imag .. "i" 
end

z = Complex(1,0) + Complex(0,2)
print(z)
```

Expected output

```
$ lua mytest.lua
1+2i
```

**Comment by jmid** [comment]
Darn, I commented on the wrong bug report :-) I just pushed a fix for this one tonight. 
Note however, I haven't implemented support for __tostring (for now), so with the fix
the body of __tostring will still be marked as unreachable for the example.
